## Case study

In [1]:
import numpy as np

In [2]:
#np.genfromtxt("cric_data.tsv", delimiter="\t", usecols=(1,2,3), names=True, dtype=int)
#The last line gives you the name of header

In [3]:
match_data=np.genfromtxt("cric_data.tsv", delimiter="\t", skip_header=1, usecols=(1,2,3))
match_data

array([[100.,  78., 342.],
       [ 11.,  62., 191.],
       [  8.,  85., 252.],
       [ 71.,  24., 307.],
       [104.,  17., 229.],
       [ 18., 104., 246.],
       [  8.,  76., 226.],
       [ 86.,  74., 288.],
       [ 12.,  60., 216.],
       [ 85.,  12., 224.],
       [ 18.,  63., 161.],
       [  4., 107., 276.],
       [  7.,  76., 283.],
       [ 37.,   4., 297.],
       [ 14.,   5., 139.],
       [  0.,  33., 224.],
       [  4.,   7., 178.],
       [  0.,   0.,   0.],
       [ 21.,  36., 193.],
       [  1.,  66., 231.],
       [ 62.,   0., 134.],
       [  0., 123., 246.],
       [138.,  39., 299.],
       [ 38.,   9., 242.],
       [  2.,  11., 214.],
       [ 46.,  14., 152.],
       [ 65.,   0., 104.],
       [  0.,   0.,   4.],
       [ 39.,  26., 155.],
       [ 48.,   4., 168.],
       [141.,  48., 282.],
       [ 62.,   7., 228.],
       [ 12.,  73., 231.],
       [  1.,  86., 238.],
       [ 41.,  32., 255.],
       [ 11.,  82., 273.],
       [  3.,  25., 143.],
 

In [4]:
match_data.shape

(225, 3)

In [5]:
Sachin=match_data[:,0]
Sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

In [6]:
Rahul=match_data[:,1]
Rahul

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  12.,  63.,
       107.,  76.,   4.,   5.,  33.,   7.,   0.,  36.,  66.,   0., 123.,
        39.,   9.,  11.,  14.,   0.,   0.,  26.,   4.,  48.,   7.,  73.,
        86.,  32.,  82.,  25., 153.,  26.,   1.,   6.,   3.,   1.,  39.,
        30.,  32.,  84.,  36.,  31.,   0.,  47.,  13.,  49.,  28.,   0.,
        28.,  19.,  13.,  14.,  11., 103.,  43.,   5.,   5.,  15.,   0.,
         5.,  30.,   4.,  53.,  60.,   7.,  74.,  71.,  54.,  13.,  69.,
        33.,  29.,   2.,   8.,  36.,  51.,   8.,  62.,   0.,  22.,  39.,
       104.,  44.,   1.,   2.,   0.,  17.,   0.,  14.,  62.,  15.,  68.,
        17.,   0.,  22.,  25.,  29.,  60.,  34.,  65.,   3.,   7.,  16.,
         0.,   4.,  53.,   5.,  23.,  82.,   3.,   0.,  20.,  21.,  80.,
        22.,   8.,  18.,  24.,  50.,   1.,  42.,  61.,   0.,   6.,  64.,
         9.,  46.,   0.,   0.,   0.,   0.,  13.,   0.,  72.,  12.,  38.,
        79.,  18.,  16.,  16.,  56.,  21.,  58.,   

In [7]:
India=match_data[:,2]
India

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 224., 161.,
       276., 283., 297., 139., 224., 178.,   0., 193., 231., 134., 246.,
       299., 242., 214., 152., 104.,   4., 155., 168., 282., 228., 231.,
       238., 255., 273., 143., 345., 134., 292., 299., 233., 332., 276.,
       264., 213., 224., 306., 259., 141., 155., 183., 309., 208., 124.,
       208., 305., 273., 186., 163., 239., 274., 182., 256., 227., 157.,
       353., 271., 211., 141., 243., 499., 229., 234., 259., 242., 223.,
       184., 125., 195., 154., 142., 197., 213., 256., 197., 177., 167.,
       366., 269., 292., 218.,   0., 199., 319., 245., 274., 208., 201.,
       275., 134.,  68., 149., 216., 407., 302., 197., 222., 224., 321.,
         0., 162., 221., 204., 213., 286., 272., 382., 229., 175., 360.,
       256., 165., 335., 188., 146., 113., 241., 211., 225.,  35., 163.,
       200., 176., 269., 284., 175.,  27., 282., 141., 229., 213., 205.,
       279.,  88., 284., 207., 224., 204., 280., 19

### Problem 1: Find mean, median, IQR for Sachin, Rahul, and India

In [8]:
heads=[Sachin, Rahul, India]
heads_name = ['Sachin', ' Rahul', 'India']
type(heads)
#Made a list of people

list

In [9]:
for i,j in zip(heads, heads_name):
    i_mean=np.mean(i)
    i_median=np.median(i)
    i_IQR=np.percentile(i,75)-np.percentile(i,25)
    print(j,"Mean", i_mean)
    print(j,"Median", i_median)
    print(j,"IQR", i_IQR)
    print("")

Sachin Mean 39.87555555555556
Sachin Median 27.0
Sachin IQR 57.0

 Rahul Mean 32.062222222222225
 Rahul Median 22.0
 Rahul IQR 46.0

India Mean 220.79555555555555
India Median 216.0
India IQR 98.0



In [10]:
def stats(i):
    print("mean", np.mean(i))
    print("median", np.median(i))
    print("IQR", np.percentile(i,75)-np.percentile(i,25))

In [11]:
stats(Sachin)

mean 39.87555555555556
median 27.0
IQR 57.0


In [12]:
stats(Rahul)

mean 32.062222222222225
median 22.0
IQR 46.0


In [13]:
stats(India)

mean 220.79555555555555
median 216.0
IQR 98.0


In [14]:
np.mean(match_data, axis=0)
#You can get mean of each column like this

array([ 39.87555556,  32.06222222, 220.79555556])

In [15]:
np.median(match_data, axis=0)
#You can get median of each column like this

array([ 27.,  22., 216.])

In [16]:
np.percentile(match_data,75, axis=0)-np.percentile(match_data,25, axis=0)
#You can get IQR of each column like this

array([57., 46., 98.])

### Problem 2: Find the histogram of Sachin's scores with 10 bins

In [17]:
np.histogram(Sachin, bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

### Problem 3: Find mean of Sachin's scores grouped by 25 matches ------------ GOOD

In [18]:
Sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

In [19]:
len(Sachin)

225

In [20]:
Sachin.shape

(225,)

In [21]:
Sachin_rearranged=Sachin.reshape((9,25))

In [22]:
np.mean(Sachin_rearranged, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

### Problem 4: Find mean of Sachin's scores where he has scored a century

In [23]:
Sachin_above99=Sachin[Sachin>99]
np.mean(Sachin_above99)

125.0

### Problem 5: Find mean of Sachin's scores when Rahul has scored less than EQUAL TO 10

In [24]:
Sachin_withRahul=Sachin[Rahul<=10]
np.mean(Sachin_withRahul)

40.2112676056338

### Problem 6: Find mean for Sachin's scores based on each quartile of India's score

In [25]:
India

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 224., 161.,
       276., 283., 297., 139., 224., 178.,   0., 193., 231., 134., 246.,
       299., 242., 214., 152., 104.,   4., 155., 168., 282., 228., 231.,
       238., 255., 273., 143., 345., 134., 292., 299., 233., 332., 276.,
       264., 213., 224., 306., 259., 141., 155., 183., 309., 208., 124.,
       208., 305., 273., 186., 163., 239., 274., 182., 256., 227., 157.,
       353., 271., 211., 141., 243., 499., 229., 234., 259., 242., 223.,
       184., 125., 195., 154., 142., 197., 213., 256., 197., 177., 167.,
       366., 269., 292., 218.,   0., 199., 319., 245., 274., 208., 201.,
       275., 134.,  68., 149., 216., 407., 302., 197., 222., 224., 321.,
         0., 162., 221., 204., 213., 286., 272., 382., 229., 175., 360.,
       256., 165., 335., 188., 146., 113., 241., 211., 225.,  35., 163.,
       200., 176., 269., 284., 175.,  27., 282., 141., 229., 213., 205.,
       279.,  88., 284., 207., 224., 204., 280., 19

In [26]:
quarts=[25,50,75,100]
quarts_name=[25,50,75,100]
for i,j in zip(quarts, quarts_name):
    print(j,"th quartile:", np.mean(Sachin[India<np.percentile(India, i)]))

25 th quartile: 19.672727272727272
50 th quartile: 28.18018018018018
75 th quartile: 31.688622754491018
100 th quartile: 39.799107142857146


### Problem 7: For every match find out who has has scored more - Sachin or Rahul

In [43]:
snr=match_data[:,0:2]
snr

array([[100.,  78.],
       [ 11.,  62.],
       [  8.,  85.],
       [ 71.,  24.],
       [104.,  17.],
       [ 18., 104.],
       [  8.,  76.],
       [ 86.,  74.],
       [ 12.,  60.],
       [ 85.,  12.],
       [ 18.,  63.],
       [  4., 107.],
       [  7.,  76.],
       [ 37.,   4.],
       [ 14.,   5.],
       [  0.,  33.],
       [  4.,   7.],
       [  0.,   0.],
       [ 21.,  36.],
       [  1.,  66.],
       [ 62.,   0.],
       [  0., 123.],
       [138.,  39.],
       [ 38.,   9.],
       [  2.,  11.],
       [ 46.,  14.],
       [ 65.,   0.],
       [  0.,   0.],
       [ 39.,  26.],
       [ 48.,   4.],
       [141.,  48.],
       [ 62.,   7.],
       [ 12.,  73.],
       [  1.,  86.],
       [ 41.,  32.],
       [ 11.,  82.],
       [  3.,  25.],
       [186., 153.],
       [ 11.,  26.],
       [ 27.,   1.],
       [ 27.,   6.],
       [ 51.,   3.],
       [ 18.,   1.],
       [ 32.,  39.],
       [146.,  30.],
       [  5.,  32.],
       [ 45.,  84.],
       [141.,

In [44]:
snr.shape

(225, 2)

In [60]:
result=np.argmax(snr, axis=1)
result

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0], dtype=int64)

In [61]:
np.where(result==0, "Sachin", "Rahul").reshape(225,1)

array([['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Sachin'],
       ['Sachin'],
       ['Rahul'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Sachin'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Sachin'],
       ['Rahul'],
       ['Rahul'],
       ['Rahul'],
       ['Rahul'],
 